default: &default
  adapter: postgresql
  encoding: unicode
  host: 127.0.0.1
  port: 5432
  username: postgres
  password: testdb
  pool: 5

development:
  <<: *default
  database: team_scheduler_development

test:
  <<: *default
  database: team_scheduler_test
