name: Test echo

on:
  schedule:
    - cron: '*/5 * * * *' # every 5 minutes
  workflow_dispatch: # allows manual trigger

jobs:
  keep-awake:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo "test"
